---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      bookworm:
        ansible_facts.python_interpreter: /usr/bin/python3
        manage_kernel: true
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        manage_suid_sgid_permissions: false
        system_upgrade: false
      testing:
        ansible_facts.python_interpreter: /usr/bin/python3
        kernel_lockdown: confidentiality
        manage_auditd: false
        manage_suid_sgid_permissions: false
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_update_moduli: true
      trixie:
        ansible_facts.python_interpreter: /usr/bin/python3
        auditd_enable_flag: 1
        manage_journal: false
        manage_kernel: true
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        manage_suid_sgid_permissions: false
platforms:
  - name: bookworm
    box: debian/bookworm64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: testing
    box: debian/testing64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: trixie
    box: bento/debian-13
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
verifier:
  name: ansible
scenario:
  name: debian
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
